Repository axoxelol1/dat257-hasse-andersson, pull requests merged in 2022-05, with the labels that each got.

#55 Fixes date and time on gasque events
  client/lib/gasque.service.ts
Labels: Bug

#110 Moves deletion after auth check
  client/pages/api/events/delete.ts
Labels: 1P

#111 Styles search and filter
  client/src/components/Filters.tsx
  client/src/components/Searchbar.tsx
Labels: 1P

#113 101 dashboard auth access
  client/package-lock.json
  client/package.json
  client/pages/dashboard/_middleware.ts
  client/pages/dashboard/index.tsx
Labels: Priority MID

#109 96 bug filter disappears
  client/pages/index.tsx
  client/src/components/Filters.tsx
  client/src/components/Page.tsx
Labels: 1P
